if __name__ == "__main__":
    from datetime import datetime as dt

    import requests

    README_PATH = "../README.md"
    README_GEN_PATH = README_PATH + ".build"

    VERSION_TAG = requests.get(
        "https://api.github.com/repos/cornellev/icp/releases/latest"
    ).json()["name"]

    with open(README_GEN_PATH, "r") as f:
        readme = {"content": f.read()}

        def put(var, text):
            readme["content"] = readme["content"].replace("{{" + var + "}}", text)

        put("DATE", str(dt.now()))
        put("VERSION", VERSION_TAG)
        put(
            "AUTHOR",
            "[Ethan Uppal](https://www.ethanuppal.com) and [Utku Melemetci](https://utku.sh)",
        )

        with open(README_PATH, "w") as f:
            f.write(
                "<!-- THIS FILE IS GENERATED AUTOMATICALLY. -->\n<!-- DO NOT EDIT THIS FILE. -->\n<!-- EDIT README.md.build INSTEAD. -->\n"
                + readme["content"]
            )
