name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-latest, macos-13]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: apt update
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt-get update
      - name: Set up Homebrew
        if: ${{ contains(matrix.os, 'macos') }}
        uses: Homebrew/actions/setup-homebrew@master
      - name: brew update
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew update

      - name: Unlink Conflicting Python
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew unlink python@3.12 || true

      - name: Reinstall Python
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install python@3.12

      - name: Force Link Python
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew link --overwrite python@3.12

      # - name: Fix Python symlink conflicts (MacOS)
      #   if: ${{ contains(matrix.os, 'macos') }}
      #   run: |
      #     brew unlink python@3.12 || true
      #     brew install python@3.12
      #     brew link --overwrite python@3.12
      # - name: Verify Python installation
      #   if: ${{ contains(matrix.os, 'macos') }}
      #   run: |
      #     which python3
      #     python3 --version
      - name: Install Eigen
        run: ${{ contains(matrix.os, 'macos') && 'brew install eigen' || 'sudo apt-get install libeigen3-dev' }}
      - name: Install SDL2
        run: ${{ contains(matrix.os, 'macos') && 'brew install SDL2' || 'sudo apt-get install libsdl2-dev' }}
      - name: Install PCL (MacOS)
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install pcl
      - name: Install PCL (Linux)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          sudo apt install libboost-all-dev
          git clone https://github.com/PointCloudLibrary/pcl.git
          cd pcl
          git checkout tags/pcl-1.14.1
          mkdir build
          cd build 
          cmake -DCMAKE_BUILD_TYPE=Release ..
          sudo make -j$(nproc) install
      - name: Install sdl-wrapper
        run: |
          git clone https://github.com/cornellev/sdl-wrapper.git
          cd sdl-wrapper
          sudo make install
      - name: Install libcmdapp2
        run: |
          git clone https://github.com/cornellev/libcmdapp2.git
          cd libcmdapp2
          sudo make install
      - name: Install libconfig
        run: |
          git clone https://github.com/cornellev/config
          cd config
          sudo make install
      - name: Install simple-test
        run: |
          git clone https://github.com/cornellev/simple-test
          cd simple-test
          sudo make install
      - name: Build all
        run: make OPT=Release
      - name: Run tests
        run: |
          make test OPT=Release
          make test_3d OPT=Release
          make test_ply OPT=Release
      - name: Run benchmarks
        run: make bench OPT=Release
      - name: Test install
        run: sudo make install
