name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_lib:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Eigen
        run: sudo apt-get install libeigen3-dev
      - name: Build library
        run: make libcevicp.a OPT=RELEASE
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: libcevicp.a
          path: libcevicp.a
  test:
    runs-on: ubuntu-22.04
    needs: build_lib
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download library
        uses: actions/download-artifact@v4
        with:
          name: libcevicp.a
      - name: Run tests
        run: make test OPT=RELEASE
  bench:
    runs-on: ubuntu-22.04
    needs: build_lib
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download library
        uses: actions/download-artifact@v4
        with:
          name: libcevicp.a
      - name: Run benchmarks
        run: make bench OPT=RELEASE
