name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_test_bench:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-latest, macos-13]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: apt update
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt-get update
      - name: brew update
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew update
      - name: Install Eigen
        run: ${{ contains(matrix.os, 'macos') && 'brew install eigen'|| 'sudo apt-get install libeigen3-dev' }}
      - name: Install SDL2
        run: ${{ contains(matrix.os, 'macos') && 'brew install SDL2'|| 'sudo apt-get install libsdl2-dev' }}
      - name: Install sdl-wrapper
        run: |
          git clone https://github.com/cornellev/sdl-wrapper.git
          cd sdl-wrapper
          sudo make install
      - name: Install libcmdapp2
        run: |
          git clone https://github.com/cornellev/libcmdapp2.git
          cd libcmdapp2
          sudo make install
      - name: Install libconfig
        run: |
          git clone https://github.com/cornellev/config
          cd config
          sudo make install
      - name: Install simple-test
        run: |
          git clone https://github.com/cornellev/simple-test
          cd simple-test
          sudo make install
      - name: Build all
        run: make OPT=Release CI=ON
      - name: Run tests
        run: make test OPT=Release CI=ON
      - name: Run benchmarks
        run: |
          otool -L ./build/bench_suite
          otool -L ./build/main
          echo $LIBRARY_PATH
          echo $LD_LIBRARY_PATH
          echo $DYLD_LIBRARY_PATH
          make bench OPT=Release CI=ON
